version: '3.8'

services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    restart: always
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - mynet
    ports:
      - '3000:3000'

  mongodb:
    image: mongo:6.0.13
    container_name: mongo_db
    restart: always
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - mynet

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - nestjs
    networks:
      - mynet

volumes:
  mongo_data:

networks:
  mynet:
    driver: bridge
