version: '3.8'

services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    restart: always
    env_file:
      - .env
    networks:
      - mynet
    ports:
      - '3000:3000'

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - nestjs
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
