version: '3'

services:
  nestjs:
    build: .
    container_name: nestjs_app
    restart: always
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx_proxy
    ports:
      - '80:80'
    depends_on:
      - nestjs
