version: '3'

services:
  nestjs:
    build: .
    container_name: nestjs_app
    restart: always
    ports:
      - '3001:3000'
    env_file:
      - .env
    environment:
      NODE_ENV: production

  mongodb:
    image: mongo:7.0
    restart: always
    ports:
      - '27017:27017'

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx_proxy
    ports:
      - '8080:80'
    depends_on:
      - nestjs
